---
name: mdformat
description: CommonMark compliant Markdown formatter.
homepage: https://github.com/executablebooks/mdformat
licenses:
  - MIT
languages:
  - Markdown
categories:
  - Formatter

source:
  id: pkg:pypi/mdformat@0.7.18
  extra_packages:
    - mdformat-gfm
    - mdformat-frontmatter
    - mdformat-footnote

bin:
  mdformat: pypi:mdformat
